# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeanne/Documents/S3/OpenGL/GLImac-Template

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeanne/Documents/S3/OpenGL/GLImac-Template

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeanne/Documents/S3/OpenGL/GLImac-Template/CMakeFiles /home/jeanne/Documents/S3/OpenGL/GLImac-Template//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeanne/Documents/S3/OpenGL/GLImac-Template/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glimac

# Build rule for target.
glimac: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glimac
.PHONY : glimac

# fast build rule for target.
glimac/fast:
	$(MAKE) $(MAKESILENT) -f glimac/CMakeFiles/glimac.dir/build.make glimac/CMakeFiles/glimac.dir/build
.PHONY : glimac/fast

#=============================================================================
# Target rules for targets named TP1_SDLtemplate

# Build rule for target.
TP1_SDLtemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_SDLtemplate
.PHONY : TP1_SDLtemplate

# fast build rule for target.
TP1_SDLtemplate/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_SDLtemplate.dir/build.make TP1/CMakeFiles/TP1_SDLtemplate.dir/build
.PHONY : TP1_SDLtemplate/fast

#=============================================================================
# Target rules for targets named TP1_exo3_structure_vertex

# Build rule for target.
TP1_exo3_structure_vertex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo3_structure_vertex
.PHONY : TP1_exo3_structure_vertex

# fast build rule for target.
TP1_exo3_structure_vertex/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo3_structure_vertex.dir/build.make TP1/CMakeFiles/TP1_exo3_structure_vertex.dir/build
.PHONY : TP1_exo3_structure_vertex/fast

#=============================================================================
# Target rules for targets named TP1_exo6_ibo_quad

# Build rule for target.
TP1_exo6_ibo_quad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo6_ibo_quad
.PHONY : TP1_exo6_ibo_quad

# fast build rule for target.
TP1_exo6_ibo_quad/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo6_ibo_quad.dir/build.make TP1/CMakeFiles/TP1_exo6_ibo_quad.dir/build
.PHONY : TP1_exo6_ibo_quad/fast

#=============================================================================
# Target rules for targets named TP1_exo5_disc

# Build rule for target.
TP1_exo5_disc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo5_disc
.PHONY : TP1_exo5_disc

# fast build rule for target.
TP1_exo5_disc/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo5_disc.dir/build.make TP1/CMakeFiles/TP1_exo5_disc.dir/build
.PHONY : TP1_exo5_disc/fast

#=============================================================================
# Target rules for targets named TP1_exo1_triangle_blanc

# Build rule for target.
TP1_exo1_triangle_blanc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo1_triangle_blanc
.PHONY : TP1_exo1_triangle_blanc

# fast build rule for target.
TP1_exo1_triangle_blanc/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo1_triangle_blanc.dir/build.make TP1/CMakeFiles/TP1_exo1_triangle_blanc.dir/build
.PHONY : TP1_exo1_triangle_blanc/fast

#=============================================================================
# Target rules for targets named TP1_exo2_triangle_couleurs

# Build rule for target.
TP1_exo2_triangle_couleurs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo2_triangle_couleurs
.PHONY : TP1_exo2_triangle_couleurs

# fast build rule for target.
TP1_exo2_triangle_couleurs/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo2_triangle_couleurs.dir/build.make TP1/CMakeFiles/TP1_exo2_triangle_couleurs.dir/build
.PHONY : TP1_exo2_triangle_couleurs/fast

#=============================================================================
# Target rules for targets named TP1_exo6_ibo_disc

# Build rule for target.
TP1_exo6_ibo_disc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo6_ibo_disc
.PHONY : TP1_exo6_ibo_disc

# fast build rule for target.
TP1_exo6_ibo_disc/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo6_ibo_disc.dir/build.make TP1/CMakeFiles/TP1_exo6_ibo_disc.dir/build
.PHONY : TP1_exo6_ibo_disc/fast

#=============================================================================
# Target rules for targets named TP1_exo4_quad

# Build rule for target.
TP1_exo4_quad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_exo4_quad
.PHONY : TP1_exo4_quad

# fast build rule for target.
TP1_exo4_quad/fast:
	$(MAKE) $(MAKESILENT) -f TP1/CMakeFiles/TP1_exo4_quad.dir/build.make TP1/CMakeFiles/TP1_exo4_quad.dir/build
.PHONY : TP1_exo4_quad/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo6_ibo

# Build rule for target.
TP1_matteo_exo6_ibo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo6_ibo
.PHONY : TP1_matteo_exo6_ibo

# fast build rule for target.
TP1_matteo_exo6_ibo/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo6_ibo.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo6_ibo.dir/build
.PHONY : TP1_matteo_exo6_ibo/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo1_triangle_blanc

# Build rule for target.
TP1_matteo_exo1_triangle_blanc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo1_triangle_blanc
.PHONY : TP1_matteo_exo1_triangle_blanc

# fast build rule for target.
TP1_matteo_exo1_triangle_blanc/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo1_triangle_blanc.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo1_triangle_blanc.dir/build
.PHONY : TP1_matteo_exo1_triangle_blanc/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo3_structure_vertex

# Build rule for target.
TP1_matteo_exo3_structure_vertex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo3_structure_vertex
.PHONY : TP1_matteo_exo3_structure_vertex

# fast build rule for target.
TP1_matteo_exo3_structure_vertex/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo3_structure_vertex.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo3_structure_vertex.dir/build
.PHONY : TP1_matteo_exo3_structure_vertex/fast

#=============================================================================
# Target rules for targets named TP1_matteo_SDLtemplate

# Build rule for target.
TP1_matteo_SDLtemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_SDLtemplate
.PHONY : TP1_matteo_SDLtemplate

# fast build rule for target.
TP1_matteo_SDLtemplate/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_SDLtemplate.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_SDLtemplate.dir/build
.PHONY : TP1_matteo_SDLtemplate/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo5_draw_disk

# Build rule for target.
TP1_matteo_exo5_draw_disk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo5_draw_disk
.PHONY : TP1_matteo_exo5_draw_disk

# fast build rule for target.
TP1_matteo_exo5_draw_disk/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo5_draw_disk.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo5_draw_disk.dir/build
.PHONY : TP1_matteo_exo5_draw_disk/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo2_triangle_couleurs

# Build rule for target.
TP1_matteo_exo2_triangle_couleurs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo2_triangle_couleurs
.PHONY : TP1_matteo_exo2_triangle_couleurs

# fast build rule for target.
TP1_matteo_exo2_triangle_couleurs/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo2_triangle_couleurs.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo2_triangle_couleurs.dir/build
.PHONY : TP1_matteo_exo2_triangle_couleurs/fast

#=============================================================================
# Target rules for targets named TP1_matteo_exo4_draw_quad

# Build rule for target.
TP1_matteo_exo4_draw_quad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP1_matteo_exo4_draw_quad
.PHONY : TP1_matteo_exo4_draw_quad

# fast build rule for target.
TP1_matteo_exo4_draw_quad/fast:
	$(MAKE) $(MAKESILENT) -f TP1_matteo/CMakeFiles/TP1_matteo_exo4_draw_quad.dir/build.make TP1_matteo/CMakeFiles/TP1_matteo_exo4_draw_quad.dir/build
.PHONY : TP1_matteo_exo4_draw_quad/fast

#=============================================================================
# Target rules for targets named TP2_exo1_triangle_couleurs

# Build rule for target.
TP2_exo1_triangle_couleurs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP2_exo1_triangle_couleurs
.PHONY : TP2_exo1_triangle_couleurs

# fast build rule for target.
TP2_exo1_triangle_couleurs/fast:
	$(MAKE) $(MAKESILENT) -f TP2/CMakeFiles/TP2_exo1_triangle_couleurs.dir/build.make TP2/CMakeFiles/TP2_exo1_triangle_couleurs.dir/build
.PHONY : TP2_exo1_triangle_couleurs/fast

#=============================================================================
# Target rules for targets named TP2_exo2_triangleGenerique

# Build rule for target.
TP2_exo2_triangleGenerique: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP2_exo2_triangleGenerique
.PHONY : TP2_exo2_triangleGenerique

# fast build rule for target.
TP2_exo2_triangleGenerique/fast:
	$(MAKE) $(MAKESILENT) -f TP2/CMakeFiles/TP2_exo2_triangleGenerique.dir/build.make TP2/CMakeFiles/TP2_exo2_triangleGenerique.dir/build
.PHONY : TP2_exo2_triangleGenerique/fast

#=============================================================================
# Target rules for targets named TP2_SDLtemplate

# Build rule for target.
TP2_SDLtemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP2_SDLtemplate
.PHONY : TP2_SDLtemplate

# fast build rule for target.
TP2_SDLtemplate/fast:
	$(MAKE) $(MAKESILENT) -f TP2/CMakeFiles/TP2_SDLtemplate.dir/build.make TP2/CMakeFiles/TP2_SDLtemplate.dir/build
.PHONY : TP2_SDLtemplate/fast

#=============================================================================
# Target rules for targets named TP2_exo3_mandelbrot

# Build rule for target.
TP2_exo3_mandelbrot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP2_exo3_mandelbrot
.PHONY : TP2_exo3_mandelbrot

# fast build rule for target.
TP2_exo3_mandelbrot/fast:
	$(MAKE) $(MAKESILENT) -f TP2/CMakeFiles/TP2_exo3_mandelbrot.dir/build.make TP2/CMakeFiles/TP2_exo3_mandelbrot.dir/build
.PHONY : TP2_exo3_mandelbrot/fast

#=============================================================================
# Target rules for targets named TP_template_SDLtemplate

# Build rule for target.
TP_template_SDLtemplate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TP_template_SDLtemplate
.PHONY : TP_template_SDLtemplate

# fast build rule for target.
TP_template_SDLtemplate/fast:
	$(MAKE) $(MAKESILENT) -f TP_template/CMakeFiles/TP_template_SDLtemplate.dir/build.make TP_template/CMakeFiles/TP_template_SDLtemplate.dir/build
.PHONY : TP_template_SDLtemplate/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TP1_SDLtemplate"
	@echo "... TP1_exo1_triangle_blanc"
	@echo "... TP1_exo2_triangle_couleurs"
	@echo "... TP1_exo3_structure_vertex"
	@echo "... TP1_exo4_quad"
	@echo "... TP1_exo5_disc"
	@echo "... TP1_exo6_ibo_disc"
	@echo "... TP1_exo6_ibo_quad"
	@echo "... TP1_matteo_SDLtemplate"
	@echo "... TP1_matteo_exo1_triangle_blanc"
	@echo "... TP1_matteo_exo2_triangle_couleurs"
	@echo "... TP1_matteo_exo3_structure_vertex"
	@echo "... TP1_matteo_exo4_draw_quad"
	@echo "... TP1_matteo_exo5_draw_disk"
	@echo "... TP1_matteo_exo6_ibo"
	@echo "... TP2_SDLtemplate"
	@echo "... TP2_exo1_triangle_couleurs"
	@echo "... TP2_exo2_triangleGenerique"
	@echo "... TP2_exo3_mandelbrot"
	@echo "... TP_template_SDLtemplate"
	@echo "... glimac"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

